spring.application.name=${SPRING_APPLICATION_NAME}

spring.config.import=optional:file:backend/.env[.properties]
logging.level.org.springframework.boot.context.config=DEBUG 

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME} 
spring.datasource.username=${DB_USERNAME} 
spring.datasource.password=${DB_PASSWORD} 

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true 
# PostgreSQL Dialect (optional with recent Hibernate versions) 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect 
spring.flyway.enabled=false
