package com.ethiorental.backend.shared.notification;

public enum NotificationType {
    PROPERTY_REGISTERED, PROPERTY_SUBMITTED, PROPERTY_VERIFIED, PROPERTY_APPROVED, PROPERTY_REJECTED, PROPERTY_DELETED,
    AGREEMENT_REQUESTED, AGREEMENT_SIGNED, AGREEMENT_APPROVED, AGREEMENT_REJECTED, LEASE_REQUEST_STATUS_CHANGED, LEASE_REQUEST_CANCELLED, LEASE_REQUEST_SIGNED,
    TAX_ASSESSED, TAX_PAYMENT_DUE, TAX_PAYMENT_RECEIVED,
    RENT_PAYMENT_RECEIVED, RENT_PAYMENT_SETTLED, ANNUAL_RENTAL_TAX_DUE, TAX_CLEARANCE_ISSUED,
    COMPLAINT_SUBMITTED, COMPLAINT_ASSIGNED, COMPLAINT_RESOLVED,
    TASK_PENDING_FOR_OFFICER,
    OTP, ACCOUNT_VERIFICATION, LOGIN_ALERT,
    LANDLORD_PAYOUT_UPDATED,
    RENT_PAYMENT_REMINDER,
    RENT_PAYMENT_OVERDUE,
    AGREEMENT_EXPIRY_REMINDER,
    AGREEMENT_EXPIRED,
    AGREEMENT_CANCELLATION_REQUESTED,
    AGREEMENT_AUTO_CANCELLED
}