package com.ethiorental.backend.shared.notification;

public enum NotificationType {
    PROPERTY_REGISTERED, PROPERTY_SUBMITTED, PROPERTY_VERIFIED, PROPERTY_APPROVED, PROPERTY_REJECTED, PROPERTY_DELETED,
    AGREEMENT_REQUESTED, AGREEMENT_SIGNED, AGREEMENT_APPROVED, AGREEMENT_REJECTED,
    TAX_ASSESSED, TAX_PAYMENT_DUE, TAX_PAYMENT_RECEIVED,
    COMPLAINT_SUBMITTED, COMPLAINT_ASSIGNED, COMPLAINT_RESOLVED,
    TASK_PENDING_FOR_OFFICER,
    OTP, ACCOUNT_VERIFICATION, LOGIN_ALERT
}